// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VerificationApp.Data;

#nullable disable

namespace VerificationApp.Migrations
{
    [DbContext(typeof(VerificationAppContext))]
    partial class VerificationAppContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VerificationApp.Models.InspectingOrganization", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("InspectingOrganizations");

                    b.HasData(
                        new
                        {
                            Id = "ddddf500-0e36-4fb4-b98d-4515fc9b8cb5",
                            Name = "Роспотребнадзор"
                        },
                        new
                        {
                            Id = "10a0480d-fc87-40a3-a119-b0f8143f7c06",
                            Name = "Роскомнадзор"
                        },
                        new
                        {
                            Id = "c65eb449-4a72-4895-9077-25487bb6e736",
                            Name = "Росстандарт"
                        },
                        new
                        {
                            Id = "4b58cc46-df09-4180-916c-5ed5de7a1718",
                            Name = "Федеральная налоговая служба"
                        },
                        new
                        {
                            Id = "227adafb-f156-4d4c-8221-4bc41584f4ec",
                            Name = "Росприроднадзор "
                        });
                });

            modelBuilder.Entity("VerificationApp.Models.SmallBusinessEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SmallBusinessEntities");

                    b.HasData(
                        new
                        {
                            Id = "45292c75-e749-4927-87e3-5787414886b6",
                            Name = "Amazon"
                        },
                        new
                        {
                            Id = "3169ed79-36de-4644-b008-980791d2ddc0",
                            Name = "Microsoft"
                        },
                        new
                        {
                            Id = "1d6cb852-c300-4e2a-8e0f-5c80e58c2da3",
                            Name = "Apple"
                        },
                        new
                        {
                            Id = "943180b0-bbc5-41c6-b74f-09a45731a4d7",
                            Name = "Meta"
                        },
                        new
                        {
                            Id = "7ca5f558-336e-4a53-9bfb-b5c9c5132f17",
                            Name = "Google"
                        });
                });

            modelBuilder.Entity("VerificationApp.Models.Verification", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly>("BeginPeriod")
                        .HasColumnType("date");

                    b.Property<string>("BusinessEntity")
                        .HasColumnType("longtext");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<DateOnly>("EndPeriod")
                        .HasColumnType("date");

                    b.Property<string>("Organization")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Verifications");
                });
#pragma warning restore 612, 618
        }
    }
}
